export enum StoragesEnum {

  ACCOUNTS = 'accounts',
  CREDIT_CARD_ACCOUNTS = 'creditCardAccounts',
  INVESTMENT_ACCOUNTS = 'investmentAccounts',
  LOAN_ACCOUNTS = 'loanAccounts',
  ONBOARDING = 'onboarding',
  ONBOARDING_ACCOUNT = 'onboardingAccount',
  ONBOARDING_PRODUCT = 'onboardingProduct',
  ONBOARDING_FACTIBILITY = 'onboardingFactibility',
  ONBOARDING_USER = 'onboardingUser',
  USER_DATA = 'userData',
  TRANSFER_DATA = 'transferData',
  BENEFICIARY = 'beneficiary',
  PAYMENTS_TRANSACTION = 'paymentsTransaction',
  PAYMENTS_AFFILITION = 'paymentAffiliation',
  ENROLLMENT_DATA = 'enrollmentData',
  ENROLLMENT_USER_DATA = 'enrollmentUserData',
  CONSUMER_NETWORKS = 'consumerNetworks',
  TRANSFER_LIMIT = 'transfer-limit',
  FREQUENT_DEVICE = 'frequentDevice',
  SESSION_DATA = 'sessionData',
  PASSWORD = 'password',
  USERNAME = 'username',
  BIOMETRIC_USER = 'biometricUser'
}
